### PR TITLE
github actions for ci

### PR DESCRIPTION
**Pull request by rscohn2**
github actions for xed

@markcharney mac is failing. Something about 32 bit mode. Do you how to fix it?

### CODE REVIEW

**Comment by rscohn2** [comment]
You can see the build here: https://github.com/rscohn2/xed/actions/runs/453022278

**Comment by markcharney** [comment]
> @markcharney mac is failing. Something about 32 bit mode. Do you how to fix it?

yeah. one does not build 32b on mac any more. I think the mac toolchain disabled 32b a while ago. using host_cpu=x86-64 would avoid the issue but I am surprised my scripts defaulted to 32b on mac. I will look into why

**Comment by markcharney** [comment]
ci.py does 32 & 64b by default. I/we will have to ask it to just do 64b on mac around line 36

**Comment by rscohn2** [comment]
mac is passing, and the other ones passed in earlier runs. I think this will be ready to merge assuming they all still pass.

https://github.com/rscohn2/xed/runs/1627089315?check_suite_focus=true

**Comment by markcharney** [comment]
awesome. thank you so much for the holiday gift! 😃

**Comment by rscohn2** [comment]
You're welcome. Happy new year!

**Pull request merged**
