### PR TITLE
Add suppressed EAX operand to VMFUNC

### PR DESCRIPTION
**Pull request by athre0z**
cumo0x8uya9fzio3

### CODE REVIEW

**Comment by markcharney** [comment]
Thanks. I'll push this (and then figure out where travis moved their python 3 installation!)

**Comment by athre0z** [comment]
Any reason why you're using an absolute path? I'd just call it using "python3", the distro will have it in the path anyways.

**Comment by markcharney** [comment]
travis is great but it has some deficiencies for my purposes. Specifically, they don't have configs where you can play with both the compiler version and the python version. Just one or the other. But they USUALLY have python2 and python3 installed somewhere on the system (when you pick a machine config where you can vary the compiler). Seems like your push encountered a VM without that specific version of python3 installed when it tested your commit. Possibly they upgraded the python3 they have  lurking in the system and I just have to go find it. (Worst case they removed it or I cannot find it, but lets cross that bridge when we get there...)

**Comment by athre0z** [comment]
I'd just invoke `apt-get install python python3` in the `before-install` clause. For one of my other libs, I even install a whole new clang (they didn't support modern clang when I wrote that):
https://github.com/zyantific/remodel/blob/master/.travis.yml#L15

**Comment by markcharney** [comment]
Thanks for the suggestion. I'll give that a try; see how long it takes.  FWIW, they appear to moved to python 3.5.3 and my script was referring to 3.5.2.  But if the install does not take too long that would be preferable.

**Comment by athre0z** [comment]
As those are binary packages, it's usually pretty quick. Sticking the the example of clang and my lib, you can see the time elapsed next to the steps:

https://travis-ci.org/zyantific/remodel

**Comment by markcharney** [comment]
Ok. I tried it; looks good. Build is finishing. Will push later today. Thanks!

**Comment by markcharney** [comment]
of course the apt-get broke the mac build. need to see if i can limit the install to linix somehow.

**Comment by athre0z** [comment]
Oh, well, yeah, makes sense, haha. In case there isn't any method for that kind of distinctions for the `before_install` directive, you could go with something like:

```sh
if [ `uname -s` = 'Linux' ]; then apt-get install python python3; fi
```

**Pull request merged**
