### PR TITLE
Make silent build actually silent

### PR DESCRIPTION
**Pull request by yulyugin**
Use verbose braced message printers to avoid message generation in silent mode.

### CODE REVIEW

**Comment by markcharney** [comment]
looks reasonable. will try it

**Comment by markcharney** [comment]
ok.  I tried  it. We need to move the verbosities around. -v 0 is pretty darn silent. -v 1 gets  too much now though. Would be nice if the  old default was -v 1. You wanna take a stab at that?

**Comment by markcharney** [comment]
and then the default should be 1. those who want  silent  can specify -v 0 (or -s or  --silent which exists).

**Comment by yulyugin** [comment]
I will work on it in background. Will update this request with the new change. Changes to mbuild will be required as well.

**Comment by yulyugin** [comment]
Updated. To be fully compatible with the old behavior it needs to be considered together with https://github.com/intelxed/mbuild/pull/34

**Comment by markcharney** [comment]
this and the  mbuild patch appear to work.  Thx. Please:
 (a)  update  the  commit mesg format to  what we discussed and 
 (b)  rebase your patch  to  the head  of XED. The merge  had some guess work because of my recent batch push
and I'll rebase/merge  these in.

**Pull request merged**
