### PR TITLE
Fix build breakage

### PR DESCRIPTION
**Pull request by zlaski**
Self-explanatory.  [Surprised that CI testing has not caught this.]

### CODE REVIEW

**Comment by markcharney** [comment]
I agree with the change; how'd you see the breakage?

**Comment by zlaski** [comment]
c:\python27\python.exe mfile.py --opt=3 --install-dir=kits/local --static --debug --verbose=3 install
cd kits/local/examples
c:\python27\python.exe mfile.py --build-cpp-examples –debug

**Comment by zlaski** [comment]
c:\python27\python.exe mfile.py --opt=3 --install-dir=kits/local --static --debug --verbose=3 install
cd kits/local/examples
c:\python27\python.exe mfile.py --build-cpp-examples –debug

I’m currently reworking xed-disasm-macho so that it can be built and run on ANY platform (I need to examine Mach-O binaries on Windows, basically).  Is this something that would interest you?

--Zem

**Comment by markcharney** [comment]
Ok. I see how the error happened. My normal build harness an environment when building the examples that has some extra include paths that it should not get. I'll remove them. Thx. 

Regarding the disas-macho-anywhere: I always get nervous about (a) copyright issues with the data structure definitions and (b) maintainability when doing stuff like that.  Maintainability could be handled a little by forcing the mac version to use the native headers.  I don't know if (a) is a real issue but I'd probably have to check with someone.

**Comment by markcharney** [comment]
re the disas-macho-anywhere: how were you going about handling the required datatypes?

**Comment by zlaski** [comment]
You do have a point about maintainability.  I think pulling in the mach-o/* files is a nonstarter (there is way too many of them, for one), but I was thinking of creating a single header containing cherry-picked values and struct definitions.  I’m also not sure what copyright issues this raises, if any.

Should Apple change the layout of Mach-O binaries in the future, chances are that xed-disasm-macho would break, anyway.

I’ll make this change on my fork; we can revisit pushing it upstream at a later date.

**Pull request merged**
