### PR TITLE
Asmparse improvements and first tests

### PR DESCRIPTION
**Pull request by grigory-rechistov**
Reworked as discussed recently.

### CODE REVIEW

**Comment by markcharney** [comment]
This looks much better. can you add the new tests directory to the list of directories to test in _run_canned_tests() in xed_mbuild.py and resubmit so that we can run the new tests?

**Comment by markcharney** [comment]
Looks like a newline in the new test 5 threw off the comparison.

```
[TESTING] ./tests/tests-syntax/test-00005
comparing restriction: ['ENC', 'DEC', 'AVX', 'AVX512X', 'AVX512PF', 'HSW', 'XOP', 'VIA'] and  test: ['ENC']
C:/projects/xed/build-27-ia32-dfltlink/examples/xed-asmparse-main -q xchg eax, ebx, ecx, edx, eax, edx, edx, edx, eax, r12, r13
Retcode 1
[STDERR] ERROR: Too many operands
[STDERR]
--- ./tests/tests-syntax/test-00005\stderr.reference
+++ current
@@ -1 +1,2 @@
 ERROR: Too many operands
+
[DIFFERENT NUMBER OF LINES] ref 1 test 2
[EXPECTED] ERROR: Too many operands
[STDERR MISMATCH]
```

**Comment by grigory-rechistov** [comment]
This problem looks familiar. Rebase scripts have some problems with passing end line symbols to reference files, and then comparison fails.

**Comment by grigory-rechistov** [comment]
It seems to affect only stderr output comparison

**Comment by markcharney** [comment]
I have not encountered that issue.

**Comment by grigory-rechistov** [comment]
Maybe it is caused by the fact that I sometimes rebase the tests on Windows hosts, and maybe at committing time CR/LF endlines are getting mangled. I will try to figure that out if it becomes annoying. For now, I have simply updated the reference file for the test

**Comment by markcharney** [comment]
git has (waaaaay too many) settings for CRLF in windows.
I tend not to use windows for committing code though.
Here's what I put in my $HOME/.gitconfig for windows: 

```
[core]
        autocrlf = true
```

**Comment by grigory-rechistov** [comment]
I will try `autocrlf` for the xed repository. I cannot make it a global config setting, because some other projects I work on depend on Unix-style line endings of certain files even on Windows...

**Pull request merged**
